# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structures.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='structures.proto',
  package='structures',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10structures.proto\x12\nstructures\"D\n\x03Key\x12 \n\x04verb\x18\x01 \x01(\x0e\x32\x12.structures.Action\x12\x0c\n\x04imsi\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x03(\x05\"\'\n\x15\x41uthenticationVectors\x12\x0e\n\x06values\x18\x01 \x03(\r\"\xa0\x01\n\x13\x44\x61tabaseInstruction\x12<\n\toperation\x18\x01 \x01(\x0e\x32).structures.DatabaseInstruction.Operation\x12\x1a\n\x12hex_encoded_object\x18\x02 \x01(\t\"/\n\tOperation\x12\n\n\x06INSERT\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x12\n\n\x06UPDATE\x10\x02\"\xd8\x01\n\x0c\x44\x61tabaseData\x12\x35\n\toperation\x18\x01 \x01(\x0e\x32\".structures.DatabaseData.Operation\x12\x0e\n\x06remote\x18\x07 \x01(\x08\x12\x11\n\townership\x18\x08 \x01(\t\x12\x0c\n\x04imsi\x18\x02 \x01(\t\x12\t\n\x01k\x18\x03 \x01(\t\x12\x0b\n\x03\x61mf\x18\x04 \x01(\t\x12\n\n\x02op\x18\x05 \x01(\t\x12\x0b\n\x03opc\x18\x06 \x01(\t\"/\n\tOperation\x12\n\n\x06INSERT\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x12\n\n\x06UPDATE\x10\x02*\x1a\n\x06\x41\x63tion\x12\x07\n\x03SET\x10\x00\x12\x07\n\x03GET\x10\x01\x62\x06proto3'
)

_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='structures.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=525,
  serialized_end=551,
)
_sym_db.RegisterEnumDescriptor(_ACTION)

Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
SET = 0
GET = 1


_DATABASEINSTRUCTION_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='structures.DatabaseInstruction.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INSERT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=257,
  serialized_end=304,
)
_sym_db.RegisterEnumDescriptor(_DATABASEINSTRUCTION_OPERATION)

_DATABASEDATA_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='structures.DatabaseData.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INSERT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=257,
  serialized_end=304,
)
_sym_db.RegisterEnumDescriptor(_DATABASEDATA_OPERATION)


_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='structures.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='verb', full_name='structures.Key.verb', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imsi', full_name='structures.Key.imsi', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='structures.Key.value', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=100,
)


_AUTHENTICATIONVECTORS = _descriptor.Descriptor(
  name='AuthenticationVectors',
  full_name='structures.AuthenticationVectors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='structures.AuthenticationVectors.values', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=141,
)


_DATABASEINSTRUCTION = _descriptor.Descriptor(
  name='DatabaseInstruction',
  full_name='structures.DatabaseInstruction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='structures.DatabaseInstruction.operation', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hex_encoded_object', full_name='structures.DatabaseInstruction.hex_encoded_object', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DATABASEINSTRUCTION_OPERATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=304,
)


_DATABASEDATA = _descriptor.Descriptor(
  name='DatabaseData',
  full_name='structures.DatabaseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='structures.DatabaseData.operation', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remote', full_name='structures.DatabaseData.remote', index=1,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ownership', full_name='structures.DatabaseData.ownership', index=2,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imsi', full_name='structures.DatabaseData.imsi', index=3,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='k', full_name='structures.DatabaseData.k', index=4,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amf', full_name='structures.DatabaseData.amf', index=5,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op', full_name='structures.DatabaseData.op', index=6,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opc', full_name='structures.DatabaseData.opc', index=7,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DATABASEDATA_OPERATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=523,
)

_KEY.fields_by_name['verb'].enum_type = _ACTION
_DATABASEINSTRUCTION.fields_by_name['operation'].enum_type = _DATABASEINSTRUCTION_OPERATION
_DATABASEINSTRUCTION_OPERATION.containing_type = _DATABASEINSTRUCTION
_DATABASEDATA.fields_by_name['operation'].enum_type = _DATABASEDATA_OPERATION
_DATABASEDATA_OPERATION.containing_type = _DATABASEDATA
DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['AuthenticationVectors'] = _AUTHENTICATIONVECTORS
DESCRIPTOR.message_types_by_name['DatabaseInstruction'] = _DATABASEINSTRUCTION
DESCRIPTOR.message_types_by_name['DatabaseData'] = _DATABASEDATA
DESCRIPTOR.enum_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'structures_pb2'
  # @@protoc_insertion_point(class_scope:structures.Key)
  })
_sym_db.RegisterMessage(Key)

AuthenticationVectors = _reflection.GeneratedProtocolMessageType('AuthenticationVectors', (_message.Message,), {
  'DESCRIPTOR' : _AUTHENTICATIONVECTORS,
  '__module__' : 'structures_pb2'
  # @@protoc_insertion_point(class_scope:structures.AuthenticationVectors)
  })
_sym_db.RegisterMessage(AuthenticationVectors)

DatabaseInstruction = _reflection.GeneratedProtocolMessageType('DatabaseInstruction', (_message.Message,), {
  'DESCRIPTOR' : _DATABASEINSTRUCTION,
  '__module__' : 'structures_pb2'
  # @@protoc_insertion_point(class_scope:structures.DatabaseInstruction)
  })
_sym_db.RegisterMessage(DatabaseInstruction)

DatabaseData = _reflection.GeneratedProtocolMessageType('DatabaseData', (_message.Message,), {
  'DESCRIPTOR' : _DATABASEDATA,
  '__module__' : 'structures_pb2'
  # @@protoc_insertion_point(class_scope:structures.DatabaseData)
  })
_sym_db.RegisterMessage(DatabaseData)


# @@protoc_insertion_point(module_scope)
