- name: Update apt package cache
  become: yes
  apt:
    upgrade: no
    update_cache: yes
    cache_valid_time: 3600

- name: "Install convenience dependencies"
  become: yes
  apt:
    name:
      - "zsh"
      - "emacs-nox"
    state: "latest"

- name: "Setup tmux config file"
  ansible.builtin.template:
    src: "templates/tmux-dotfile.j2"
    dest: "/home/{{ primary_login_user }}/.tmux.conf"

- name: "Use zsh for sanity"
  become: yes
  user:
    name: "{{ primary_login_user }}"
    shell: /bin/zsh

- name: "Setup zshrc config file"
  ansible.builtin.template:
    src: "templates/zshrc-dotfile.j2"
    dest: "/home/{{ primary_login_user }}/.zshrc"
