# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define :ueransim do |ueransim|
    ueransim.vm.box = "debian/contrib-buster64"
    ueransim.vm.hostname = "ueransim"
  
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    ueransim.vm.network "private_network", ip: "192.168.40.200"

    ueransim.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "3"]

    end

    ueransim.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.host_key_checking = false
      ansible.playbook = "ansible/ueransim.yml"
      ansible.raw_arguments = ['--timeout=20']
      ansible.verbose = 'v'
    end

  end