[package]
name = "auth-vector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
milenage = "0.1.3"
rand = "0.8.4"
sha2 = "0.9"
hmac = "0.11"
hex = "0.4.3"
