directory:
  hostname: "100.115.171.79"
  id: "AWS-directory"
  is_vagrant: false

ueransim:
  hostname: "100.108.62.90"
  id: "Boron-ueransim"
  is_vagrant: false

services:
  - hostname: "100.115.171.79"
    id: "AWS-service"
    is_vagrant: false
