directory:
  hostname: "100.88.189.43"
  id: "Azure-directory"
  is_vagrant: false

ueransim:
  hostname: "100.108.62.90"
  id: "Boron-ueransim"
  is_vagrant: false

services:
  - hostname: "100.88.189.43"
    id: "Azure-service"
    is_vagrant: false
