directory:
  hostname: "100.76.33.70"
  id: "Cobble-directory"
  is_vagrant: false

ueransim:
  hostname: "100.87.240.90"
  id: "Prothean-ueransim"
  is_vagrant: false

services:
  - hostname: "100.76.33.70"
    id: "Cobble-service"
    is_vagrant: false
