directory:
  hostname: "100.78.102.100"
  id: "Hestia-directory"
  is_vagrant: false

ueransim:
  hostname: "100.108.62.90"
  id: "Boron-ueransim"
  is_vagrant: false

services:
  - hostname: "100.78.102.100"
    id: "Hestia-service"
    is_vagrant: false
