# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network/protos/debugping.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='network/protos/debugping.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1enetwork/protos/debugping.proto\"\x1b\n\x0bPingMessage\x12\x0c\n\x04time\x18\x01 \x01(\x01\"\x19\n\tPingReply\x12\x0c\n\x04time\x18\x01 \x01(\x01\x32\x34\n\tDebugPing\x12\'\n\tDebugPing\x12\x0c.PingMessage\x1a\n.PingReply\"\x00\x62\x06proto3'
)




_PINGMESSAGE = _descriptor.Descriptor(
  name='PingMessage',
  full_name='PingMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='PingMessage.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=61,
)


_PINGREPLY = _descriptor.Descriptor(
  name='PingReply',
  full_name='PingReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='PingReply.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['PingMessage'] = _PINGMESSAGE
DESCRIPTOR.message_types_by_name['PingReply'] = _PINGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingMessage = _reflection.GeneratedProtocolMessageType('PingMessage', (_message.Message,), {
  'DESCRIPTOR' : _PINGMESSAGE,
  '__module__' : 'network.protos.debugping_pb2'
  # @@protoc_insertion_point(class_scope:PingMessage)
  })
_sym_db.RegisterMessage(PingMessage)

PingReply = _reflection.GeneratedProtocolMessageType('PingReply', (_message.Message,), {
  'DESCRIPTOR' : _PINGREPLY,
  '__module__' : 'network.protos.debugping_pb2'
  # @@protoc_insertion_point(class_scope:PingReply)
  })
_sym_db.RegisterMessage(PingReply)



_DEBUGPING = _descriptor.ServiceDescriptor(
  name='DebugPing',
  full_name='DebugPing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=90,
  serialized_end=142,
  methods=[
  _descriptor.MethodDescriptor(
    name='DebugPing',
    full_name='DebugPing.DebugPing',
    index=0,
    containing_service=None,
    input_type=_PINGMESSAGE,
    output_type=_PINGREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEBUGPING)

DESCRIPTOR.services_by_name['DebugPing'] = _DEBUGPING

# @@protoc_insertion_point(module_scope)
