# The id of this network
id: "default-network-id"

# Address this network will host on for remote facing RPCs
host_addr: "0.0.0.0:50052"

# Address this network will host on for local facing RPCs
local_auth_addr: "127.0.0.1:50051"

# Address of the directory service
directory_addr: "127.0.0.1:8900"

# Keyfile for ed25519 keys used in signing remote messages
ed25519_keyfile_path: "./out/dauth_service/default/ed25519_keys"

# Path to create/find the database
database_path: "./out/dauth_service/default/network_state_db.sqlite3"

# Delay in seconds before tasks thread begins executing
task_startup_delay: 1.0

# Interval in seconds between checking for new tasks
task_interval: 1.0

# The number of vector slices possible (also determines max backup networks)
# Slice 0 is always reserved for the home network
num_sqn_slices: 32

# Max number of auth vectors a backup network should have at one time
max_backup_vectors: 10

# Network PLMN configuration
mcc: "901"
mnc: "70"

# The set of users for this network (for testing)
users: { 
   "imsi-901700000000001": {
    "k": "465B5CE8B199B49FAA5F0A2EE238A6BC",
    "opc": "E8ED289DEBA952E4283B54E88E6183CA",

    # Mapping of sqn slice to max sqn for that slice
    "sqn_slice_max": {
      0: 32
    },

    # Mapping of network id to sqn slice
    "backup_network_ids": { }
  }
}
