# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import messaging_pb2 as messaging__pb2


class MessagingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendLogMessages = channel.stream_unary(
        '/Messaging/SendLogMessages',
        request_serializer=messaging__pb2.LogMessage.SerializeToString,
        response_deserializer=messaging__pb2.LogResponse.FromString,
        )


class MessagingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendLogMessages(self, request_iterator, context):
    """Client sends a stream of messages
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessagingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendLogMessages': grpc.stream_unary_rpc_method_handler(
          servicer.SendLogMessages,
          request_deserializer=messaging__pb2.LogMessage.FromString,
          response_serializer=messaging__pb2.LogResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Messaging', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
