# The id of this network
id: "colte-1"

# Address this network will host on
host_addr: "192.168.56.101:50051"

# Address of the directory service
directory_addr: "192.168.56.250:8900"

# Keyfile for ed25519 keys used in signing remote messages
ed25519_keyfile_path: "/var/lib/dauth/dauth_service/ed25519_keys"

# Path to create/find the database
database_path: "/var/lib/dauth/dauth_service/dauth.sqlite3"

# Delay in seconds before tasks thread begins executing
task_startup_delay: 1.0

# Interval in seconds between checking for new tasks
task_interval: 1.0

# The number of vector slices possible (also determines max backup networks)
# Slice 0 is always reserved for the home network
num_sqn_slices: 32

# Max number of auth vectors a backup network should have at one time
max_backup_vectors: 10

# The set of users for this network (for testing)
users: {
  "imsi-901700000000001": {
    "k": "465B5CE8B199B49FAA5F0A2EE238A6BC",
    "opc": "E8ED289DEBA952E4283B54E88E6183CA",

    # Mapping of sqn slice to max sqn for that slice
    "sqn_slice_max": {
      0: 32,
      1: 33,
      2: 34
    },

    # Mapping of network id to sqn slice
    "backup_network_ids": {
      "colte-2": 1
    }
  },
  "imsi-901700000000011": {
    "k": "11111111111111111111111111111111",
    "opc": "E8ED289DEBA952E4283B54E88E6183CA",

    # Mapping of sqn slice to max sqn for that slice
    "sqn_slice_max": {
      0: 32,
      1: 33,
      2: 34
    },

    # Mapping of network id to sqn slice
    "backup_network_ids": {
      "colte-2": 1
    }
  },
  "imsi-901700000000012": {
    "k": "22222222222222222222222222222222",
    "opc": "E8ED289DEBA952E4283B54E88E6183CA",

    # Mapping of sqn slice to max sqn for that slice
    "sqn_slice_max": {
      0: 32,
      1: 33,
      2: 34
    },

    # Mapping of network id to sqn slice
    "backup_network_ids": {
      "colte-2": 1
    }
  }
}
