# Addrs of remote cores that can be contacted
remote_addrs:
  - "[::1]:50052"

# Address to host the RPC server
host_addr: "[::1]:50051"

# User sensitive data for generating auth vectors
# Key is imsi/supi
users:
  "901700000000001":
    k: "465B5CE8B199B49FAA5F0A2EE238A6BC"
    opc: "E8ED289DEBA952E4283B54E88E6183CA"
    sqn_max: "32"

# min and max values for user id (imsi/supi) to be considered local
local_user_id_min: "901700000000001"
local_user_id_max: "901700000000001"

# keyfile for ed25519 keys used in signing remote messages
ed25519_keyfile_path: "~/dauth_service/ed25519_keys"

# path to create/find the database
database_path: "~/dauth_service/sqlite1.db"
