---

- name: Set up a local isolated vm for colte development
  hosts: ['colte1', 'colte2']
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  roles:
    - "ssh_mesh_member"

  tasks:
    - name: Update apt package cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: "Install convenience dependencies"
      apt:
        name:
          - "zsh"
        state: "present"

    - name: Install open5gs and dauth runtime dependencies
      apt:
        name:
          - software-properties-common
          - libbson-1.0-0
          - libidn11
          - libmicrohttpd12
          - libmongoc-1.0-0
          - libsctp1
          - libtins4.0
          - mongodb
        state: present

    - name: Copy network config
      copy:
        src: "../configs/network/{{ inventory_hostname }}.yaml"
        dest: "/etc/netplan/60-static-routes.yaml"
        remote_src: no

    - name: Copy scripts
      copy:
        src: "../scripts/"
        dest: "/home/vagrant/scripts"
        remote_src: no
        mode: u=rwx,g=rwx,o=rwx

    - name: Apply network changes
      command: netplan apply
      become: yes

    - name: Configure forwarding and rounting (script)
      command: /home/vagrant/scripts/configure-fwd
      become: yes

    - name: Create dauth config directory if it doesn't already exist
      file:
        path: /etc/dauth
        state: directory

    - name: Write host data to a long-lived config file
      ansible.builtin.template:
        src: "templates/dauth-host-config.yml.j2"
        dest: "/etc/dauth/host-config.yml"

    # - name: Configure open5gs ips
    #   command: /home/vagrant/scripts/open5gs-ip-config.py {{ colte_ip }}
    #   become: yes

    - name: "Setup tmux config file"
      ansible.builtin.template:
        src: "templates/tmux-dotfile.j2"
        dest: "/home/vagrant/.tmux.conf"

    - name: "Use zsh for sanity"
      become: yes
      user:
        name: "vagrant"
        shell: /bin/zsh

    - name: "Setup zshrc config file"
      ansible.builtin.template:
        src: "templates/zshrc-dotfile.j2"
        dest: "/home/vagrant/.zshrc"

    - name: "Copy in config file"
      copy:
        src: "../configs/dauth-service/sample{{test_net_index}}.yaml"
        dest: "/etc/dauth/dauth.yml"
        remote_src: no
