---

- name: Set up a local isolated vm for dAuth development
  hosts: [
    "*"
  ]
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: no

  tasks:
    - name: Update apt package cache
      become: yes
      apt:
        upgrade: no
        update_cache: yes

    - name: Install open5gs dependencies
      become: yes
      apt:
        name:
          - software-properties-common
          - python3-pip
          - python3-setuptools
          - python3-wheel
          - ninja-build
          - build-essential
          - flex
          - bison
          - git
          - libsctp-dev
          - libgnutls28-dev
          - libgcrypt-dev
          - libssl-dev
          - libidn11-dev
          - libmongoc-dev
          - libbson-dev
          - libyaml-dev
          - libnghttp2-dev
          - libmicrohttpd-dev
          - libcurl4-gnutls-dev
          - libnghttp2-dev
          - libtins-dev
          - meson
        state: latest

    - name: Install open5gs runtime dependencies
      become: yes
      apt:
        name:
          - mongodb
        state: latest

    - name: Start mongo
      systemd:
        name: mongodb
        state: started
        enabled: yes

    - name: Add open5gs repo
      become: yes
      apt_repository:
        repo: ppa:open5gs/latest

    - name: Copy network config
      become: yes
      copy:
        src: "../configs/network/{{ inventory_hostname }}.yaml"
        dest: "/etc/netplan/60-static-routes.yaml"
        remote_src: no

    - name: Apply network changes
      command: netplan apply
      become: yes

    - name: Copy scripts
      copy:
        src: "../scripts/"
        dest: "/home/vagrant/scripts"
        remote_src: no
        mode: u=rwx,g=rwx,o=rwx

    # - name: Configure forwarding and rounting (script)
    #   command: /home/vagrant/scripts/configure-fwd
    #   become: yes

    # - name: Install open5gs
    #   apt:
    #     name: open5gs
    #     state: present

    # - name: Configure open5gs ips
    #   command: /home/vagrant/scripts/open5gs-ip-config.py {{ colte_ip }}
    #   become: yes

    # - name: Restart amf service
    #   systemd:
    #     name: open5gs-amfd
    #     state: restarted
    #     enabled: yes

    # - name: Start smf service
    #   systemd:
    #     name: open5gs-smfd
    #     state: started
    #     enabled: yes

    # - name: Start upf service
    #   systemd:
    #     name: open5gs-upfd
    #     state: started
    #     enabled: yes
