---

- name: Set up a directory service machine
  hosts: ['directory']
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  roles:
    - "ssh_mesh_member"
    - "dev_login"

  tasks:
    - name: Create dauth config directory if it doesn't already exist
      file:
        path: /etc/dauth
        state: directory

    - name: Write host data to a long-lived config file
      template:
        src: "templates/dauth-host-config.yaml.j2"
        dest: "/etc/dauth/host-config.yaml"

    - name: "Copy in config file"
      copy:
        src: "../configs/directory-service/directory.yaml"
        dest: "/etc/dauth/directory.yaml"
        remote_src: no
      register: dauth_directory_config

    - name: Restart Directory Due to Config Change
      systemd:
        name: dauth-directory
        state: restarted
      when: dauth_directory_config.changed
