---

- name: Set up a directory service machine
  hosts: ['directory']
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  roles:
    - "ssh_mesh_member"

  tasks:
    - name: Update apt package cache
      become: yes
      apt:
        upgrade: no
        update_cache: yes
        cache_valid_time: 3600

    - name: "Install convenience dependencies"
      apt:
        name:
          - "zsh"
          - "emacs-nox"
        state: "latest"

    - name: Create dauth config directory if it doesn't already exist
      file:
        path: /etc/dauth
        state: directory

    - name: Write host data to a long-lived config file
      ansible.builtin.template:
        src: "templates/dauth-host-config.yml.j2"
        dest: "/etc/dauth/host-config.yml"

    - name: "Setup tmux config file"
      ansible.builtin.template:
        src: "templates/tmux-dotfile.j2"
        dest: "/home/vagrant/.tmux.conf"

    - name: "Use zsh for sanity"
      become: yes
      user:
        name: "vagrant"
        shell: /bin/zsh

    - name: "Setup zshrc config file"
      ansible.builtin.template:
        src: "templates/zshrc-dotfile.j2"
        dest: "/home/vagrant/.zshrc"
