---

- name: Set up a local isolated vm for using ueransim
  hosts: ['ueransim']
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  roles:
    - "ssh_mesh_member"
    - "dev_login"

  tasks:
    - name: Add kitware key
      apt_key:
        url: "https://apt.kitware.com/keys/kitware-archive-latest.asc"
        state: present

    - name: Add kitware repos for latest cmake
      apt_repository:
        repo: "deb https://apt.kitware.com/ubuntu/ focal main"
        state: present
        update_cache: yes

    - name: Update apt package cache
      become: yes
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - "g++"
          - "libsctp-dev"
          - "lksctp-tools"
          - "software-properties-common"
          - "lsb-release"
          - "cmake"
        state: present

    # - name: Clone UERANSIM
    #   git:
    #     repo: https://github.com/aligungr/UERANSIM
    #     dest: /home/vagrant/UERANSIM
    #     version: v3.2.6

    # - name: Make UERANSIM
    #   make:
    #     chdir: /home/vagrant/UERANSIM

    - name: Copy ueransim configs
      copy:
        src: "../configs/ueransim"
        dest: "/home/vagrant/configs"
        remote_src: no
        mode: u=rwx,g=rwx,o=rwx

    - name: Copy scripts
      copy:
        src: "../scripts/"
        dest: "/home/vagrant/scripts"
        remote_src: no
        mode: u=rwx,g=rwx,o=rwx

    - name: Copy network config
      copy:
        src: "../configs/network/ueransim.yaml"
        dest: "/etc/netplan/60-static-routes.yaml"
        remote_src: no

    - name: Apply network changes
      command: netplan apply
      become: yes
