# The id of this network
id: "sample-network-2"

# Address this network will host on
host_addr: "127.0.0.1:50052"

# Address of the directory service
directory_addr: "127.0.0.1:8900"

# Keyfile for ed25519 keys used in signing remote messages
ed25519_keyfile_path: "./out/sample-network-2/dauth_service/ed25519_keys"

# Path to create/find the database
database_path: "./out/sample-network-2/dauth_service/sqlite1.db"

# Delay in seconds before tasks thread begins executing
task_startup_delay: 5.0

# Interval in seconds between checking for new tasks
task_interval: 10.0

# The set of users for this network (for testing)
users: {
  "imsi-901700000000002": {
    "k": "465B5CE8B199B49FAA5F0A2EE238A6BC",
    "opc": "E8ED289DEBA952E4283B54E88E6183CA",
    "sqn_max": "33",
    "sqn_slice": 1,
    "backup_network_ids": [
      "sample-network-1"
    ]
  }
}
