# The list of users to add
users: [
  {
    # User info
    "user_id": "imsi-901700000000002",
    "k": "465B5CE8B199B49FAA5F0A2EE238A6BC",
    "opc": "E8ED289DEBA952E4283B54E88E6183CA",

    # current sqn_max for the home network (slice 0)
    "sqn_max": 32,

    # Set of backups for this user
    "backups": [
      {
        "backup_id": "some-backup-id",
        "sqn_slice": 1,
        "sqn_max": 33,
      }
    ]
  }
]
